### ISSUE TITLE
getReactNativeDimensions throws exception with react-native-windows

### ISSUE THREAD

**Issue by adam-bratin** [infinitered/reactotron-react-native#111]
https://github.com/infinitered/reactotron-react-native/blob/4d66d10a49a0a50e032c1d34cbd26b3799fcbf0c/src/helpers/getReactNativeDimensions.ts#L35

this line throws an exception when run on a react-native-windows App because they have not implemented the screen dimension.

Expected Behavior:
App is able to load correctly

Actual behaviour:
App throws exception Cannot Get Dimension with key screen

**Comment by rmevans9** [comment]
Hmm... I am not too familiar with `react-native-windows`. Do you know if there is a way we can emulate the behavior we are using `Dimensions.get("screen")` for?

**Comment by adam-bratin** [comment]
@rmevans9 Thanks for the quick reply. I am not exactly sure why you are using the screen dimensions, but in Window UWP a developer can only access the dimensions of the window of their application they do not get the full dimensions of the current screen. This is why RNW does not implement Dimensions.get("screen"). I think the best approach would be to try catch reading this value. That would at least prevent the crash and then try and figure out a default value you want to use in this scenario. Currently I am patching the dist js file to try catching retrieving the diemensions and am passing undefined and every looks to still work.

**Comment by rmevans9** [comment]
@adam-bratin we pull the dimensions as a part of the meta information we send with a connection to show in the "Home" tab in reactotron. Not very important overall however not sending it could make things look a little funny in reactotron. Does `Dimensions.get("window")` work in RNW?

**Comment by adam-bratin** [comment]
@rmevans9 As far as I know it does work.

**Comment by rmevans9** [comment]
Ok, I will add this to my list to resolve soon. I will either try/catch it out and send nothing or send `Dimensions.get("window")` for RNW.

**Comment by adam-bratin** [comment]
great thanks.

**Comment by rmevans9** [comment]
This will be fixed in `reactotron-react-native` 3.6.3 (releasing within a few min if nothing goes wrong)
