### ISSUE TITLE
Update to use new community AsyncStorage

### ISSUE THREAD

**Issue by josephmbeveridge** [infinitered/reactotron-react-native#14]
As of RN 0.59.0 (still on rc3 today) AsyncStorage has been moved to https://github.com/react-native-community/react-native-async-storage and a warning is being shown if you are using the old core version.

https://github.com/infinitered/reactotron-react-native/blob/ab4444d0d8f467ef603b0e92b8217e7fd3c4deff/src/reactotron-react-native.ts#L1 still references the old version from core.

**Comment by rmevans9** [comment]
Hey @josephmbeveridge!

Thanks for the heads up. I was just thinking about what the plan is going to be for resolving this upcoming issue. I should hopefully have a fix for this by this weekend.

**Comment by rmevans9** [comment]
Just a quick update here. I have the changes in a branch and will be doing further testing of them before doing a release. It will be a breaking change when it lands!

**Comment by pvinis** [comment]
Do you think you will add it in peerDeps or deps?

**Comment by rmevans9** [comment]
peerDeps @pvinis

**Comment by rmevans9** [comment]
An update here - I am waiting to see if metro gets updated to allow for optional requires. If they do I can do this in a backward compatible way, if they don't this will likely have to be a breaking change.

**Comment by nitaking** [comment]
I created.
https://github.com/infinitered/reactotron-react-native/pull/128

**Comment by rmevans9** [comment]
There is a beta version of `reactotron-react-native` now available that should solve for this issue. Please try it and report any issues found.

https://github.com/infinitered/reactotron-react-native/releases

**Comment by wsdt** [comment]
Still having this issue.

**Comment by rezaarifian** [comment]
Still having this issue on release mode App crash on Android

**Comment by minhthong095** [comment]
still having

**Comment by aevaldas** [comment]
Upgraded `reactotron-react-native` to `4.0.3`, the issue persists
