### ISSUE TITLE
No async storage Timeline events in 4.0.0-beta.1

### ISSUE THREAD

**Issue by Ashoat** [infinitered/reactotron-react-native#146]
Hi there, first of all thanks for the great debugging tool! Very much appreciate everything you guys do for the community.

I'm trying the new `reactotron-react-native@4.0.0-beta.1` to see if I can get it working with the community `AsyncStorage`. I'm able to call the new `setAsyncStorageHandler` function without erroring, but I don't see any Async Storage Mutations in my Timeline tab. I've made sure to select the Async Storage Mutations option in the filter view.

I'm using:

- `reactotron-react-native@4.0.0-beta.1`
- `@react-native-community/async-storage@1.3.0`
- `react-native@0.59.8`
- `reactotron-redux@3.1.1`
- Reactotron 2.16.0
- macOS 10.14.6

Here's the change I made to try and set the community `AsyncStorage`:

```diff
--- a/native/reactotron.js
+++ b/native/reactotron.js
@@ -1,5 +1,7 @@
 // @flow

+import AsyncStorage from '@react-native-community/async-storage';
+
 let reactotron = null;
 if (__DEV__) {
   const { default: Reactotron } = require('reactotron-react-native');
@@ -8,6 +10,7 @@ if (__DEV__) {
     .configure()
     .useReactNative()
     .use(reactotronRedux())
+    .setAsyncStorageHandler(AsyncStorage)
     .connect();
 }
```

Let me know if there's any other info I can provide! And apologies if I'm missing something obvious.

**Comment by rmevans9** [comment]
Can you put the `setAsyncStorageHandler`call before `useReactNative`? I am wondering if we don't handle them being out of order well.

**Comment by Ashoat** [comment]
That did it!

**Comment by rmevans9** [comment]
Awesome! I guess we should probably look to make it a bit more resilient to ordering of the calls

**Comment by jckw** [comment]
It would be great to move this library over to @react-native-community/async-storage! Using both the deprecated AsyncStorage and the community-managed version [creates race conditions and hard-to-debug issues](https://github.com/react-native-community/async-storage/issues/12#issuecomment-526068090).

**Comment by rmevans9** [comment]
@jckw the intention of the `setAsyncStorageHandler` is that you can use whichever one your app uses. Pass either one in and it should work as expected!
