### ISSUE TITLE
Typescript: An argument for 'options' was not provided

### ISSUE THREAD

**Issue by henriquejensen** [infinitered/reactotron-react-native#162]
I am configuring the Reactotron, but I got an error with typescript because I am not passing options to `useReactNative` function.

```
Reactotron.configure()
  .useReactNative()
  .connect()
``` 

I was looking at the code and saw that the options parameter is required but all options attributes are optional. Should not be the options be optional in this case?

code link: https://github.com/infinitered/reactotron-react-native/blob/master/src/reactotron-react-native.ts#L63

**Comment by rmevans9** [comment]
Yes, we should change the options to be optional. For now you can pass an empty object
