### ISSUE TITLE
rn-host-detect: TypeError: arguments[0].indexOf is not a function

### ISSUE THREAD

**Issue by airandfingers** [infinitered/reactotron-react-native#165]
Hi, after adding your library, I observed the error described in and fixed by https://github.com/jhen0409/rn-host-detect/pull/8:

> TypeError: arguments[0].indexOf is not a function. (In 'arguments[0].indexOf('Requiring module \'NativeModules\' by name')', 'arguments[0].indexOf' is undefined)

I found a workaround (enabling "Debug JS Remotely" to avoid using `rn-host-detect`'s `console.warn` polyfill, but as long as that polyfill is broken, `reactotron` should not depend on `rn-host-detect`.

**Comment by rmevans9** [comment]
That is a fair assessment. I have been considering options here already. I haven't had time to act upon those thoughts just yet though.

**Comment by airandfingers** [comment]
https://github.com/jhen0409/rn-host-detect/pull/8 was merged into `rn-host-detect`, so this issue should now be fixed by upgrading to `rn-host-detect@1.1.6` in https://github.com/infinitered/reactotron-react-native/pull/195.

**Comment by treymo** [comment]
Could #195 be merged now?  All the checks have passed.  This bug in rn-host-detect bit me as well

**Comment by rmevans9** [comment]
I’ll look to get it merged tonight

**Comment by treymo** [comment]
Awesome! Thanks, and looking forward to it

**Comment by reyalpsirc** [comment]
When will the merge happen?

**Comment by rmevans9** [comment]
Sorry for the incredibly long delay. I released a version with this merged just now.
