### ISSUE TITLE
setAsyncStorageHandler - Cannot invoke an object which is possibly 'undefined'

### ISSUE THREAD

**Issue by 15matias15** [infinitered/reactotron-react-native#168]
Hi guys, I'm using `"reactotron-react-native": "4.0.0-beta.2"` and in the moment that I import asyncStorage and provide it to setAsyncStorageHandler, I'm getting this message from Typescript: 
 `(property) ReactotronReactNative.setAsyncStorageHandler?: ((asyncStorage: any) => Reactotron<ReactotronReactNative> & ReactotronReactNative) | undefined
Cannot invoke an object which is possibly 'undefined'.ts(2722)`
The config of reactotron is: 
```
Reactotron.configure({
  name: 'Ignite App',
  host: DebugConfig.reactotronHost,
})
  .useReactNative()
  .setAsyncStorageHandler(AsyncStorage)
  .use(reduxPlugin({ onRestore: Immutable }))
  .use(sagaPlugin({}))
  .connect();

```
```
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.36 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v11.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4
    typescript: 3.5.3
```

**Comment by rmevans9** [comment]
Hey! Sorry for the delay. Yeah, the typings for that are set as optional. You should be able to do this to get it working:

`.setAsyncStorageHandler!(asyncStorage)`

**Comment by 15matias15** [comment]
Ok

**Comment by chocky335** [comment]
@15matias15 It should help: `npm start -- --reset-cache`

**Comment by AlexandreBonfim** [comment]
![Screenshot 2019-11-17 at 21 47 34](https://user-images.githubusercontent.com/25756055/69013956-b29aa100-0985-11ea-9e51-a4a63a5fa682.png)

Still broken.
