### ISSUE TITLE
Multiple connections - one new after each app reload [Android only]

### ISSUE THREAD

**Issue by k3nda** [infinitered/reactotron-react-native#186]
**Version:** 3.x.x and higher (working on 2.2.0)
**Platform:** Android (iOS is working)
**Steps to reproduce:** 

1. start app on Android device (tested on Android 8.0.0 sdk 26)
2. check number of connection in the bottom left corner in Reactotron, there should be 1 connection
3. reload your app in emulator
4. and new connection appears and now you have 2 connections. This continues with every other reload adds one new connection

On version 2.2.0 working correctly - after app reload still have 1 connection.

**Comment by rmevans9** [comment]
Hello, can you please show your reactotron configuration?

**Comment by k3nda** [comment]
```import Reactotron, { asyncStorage } from 'reactotron-react-native'
import { reactotronRedux } from 'reactotron-redux'
import sagaPlugin from 'reactotron-redux-saga'

const reactotron = Reactotron
  .configure()
  .use(reactotronRedux())
  .use(sagaPlugin())
  .use(asyncStorage())
  .useReactNative()
  .connect()

export default reactotron```

**Comment by rmevans9** [comment]
Looks like you are missing the change needed for 4.0.0. Please check the breaking change section of this release:

https://github.com/infinitered/reactotron-react-native/releases/tag/v4.0.0

**Comment by k3nda** [comment]
Ah thanks, that helped :+1:
