### ISSUE TITLE
react-native (w/ reactotronRedux()) freezing & crashing app 

### ISSUE THREAD

**Issue by crobinson42** [infinitered/reactotron-react-native#2]
I'm experiencing my app locking up and eventually crashing when using `reactotronRedux()` - there are no errors in my logs and this happens when an action is dispatched, but not every action. I have great test coverage in my app it has been working fine for over a year so I'm not suspicious of my codebase. 

I'd love to help debug this issue I just don't know where to start. Here's a gist for my Redux store setup and also my `ReactotronConfig.js`:

https://gist.github.com/crobinson42/2be87c7c139d9a42c1217345b9e7d5c7

```
react-native: 0.57.4
reactotron: 2.4.4 (2.4.4.154)
```

-------------------

EDIT: This issue is related to `<Button onPress={dispatchSomeAction}>` and Reactotron trying to serialize the `event` passed as an argument to the `dispatchSomeAction` function.

**Comment by rmevans9** [comment]
@crobinson42 let me know if 2.1.4 works for you!

**Comment by crobinson42** [comment]
@rmevans9 I'm using v2.6 and now experiencing this same error 🤔

**Comment by rmevans9** [comment]
@crobinson42 I am not sure I follow - is this working right now?
