### ISSUE TITLE
Reactotron.log + typescript - cannot invoke an object which is possibly 'undefined'

### ISSUE THREAD

**Issue by doronnac** [infinitered/reactotron-react-native#239]
reactotron-react-native v4.0.3

```
import Reactotron from 'reactotron-react-native'
Reactotron.log() // <-- Cannot invoke an object which is possibly 'undefined'
```
Saw a similar issue which was supposedly resolved. Maybe I'm missing something?

**Comment by DavidNeiOs** [comment]
I found a temporary solution in this thread https://github.com/infinitered/reactotron-react-native/issues/168#issuecomment-535280418 
@doronnac

**Comment by leotm** [comment]
Since in our `ReactotronCore` _interface_ `log?: (...args: any[]) => void` is an optional _function_, we just need to assert its not null when calling it

```tsx
Reactotron.log!('hey there')
```

Same goes for any other optional functions you're calling like `warn`, `error`, etc

**Comment by patrick-narciso** [comment]
The @leotm solution is correct, it even works for other cases such as when using `Reactotron.createEnhancer!()`

**Comment by david-bishop-levelstudio** [comment]
> Hey Patrick... you mean in the store configuration? How did you do it ? thanks

Something like this:

```
import { createStore } from "redux";
import Reactotron from "../ReactotronConfig";

import rootReducer from "./reducers";

export default createStore(rootReducer, Reactotron.createEnhancer!());
```

**Comment by GermaVinsmoke** [comment]
But this solution gives this warning - "Forbidden non-null assertion."
Is it okay to have this warning?
