### ISSUE TITLE
Why most of Reactotron props are "optional" in typescript?

### ISSUE THREAD

**Issue by italomlp** [infinitered/reactotron-react-native#60]
Why most of the props of Reactotron are optional? As we can see in the following file (and another lines of it), most of the props has the `?`, that makes Typescript assumes they can be null or undefined too.
https://github.com/infinitered/reactotron-react-native/blob/master/src/reactotron-react-native.ts#L62

I'm using it in my React Native app, and recently migrate for Typescript. When I set `console.tron` to point to my Reactotron instance, came across with `Cannot invoke an object which is possibly 'undefined'.` in most of the functions, like `createEnhancer`, `log` and `logImportant`. I'm extending my global namespace, declaring property `tron` inside of `Console`, that has type Reactotron exported from `reactotron-core-client`.

Maybe `reactotron-react-native` can has its own type for Reactotron, and export it for developers use. Or, maybe, the `reactotron-core-client` can declare Reactotron type without the optional flag (if this is the case, I'll open an issue on its repository).

My doubt is if these props are really optional or not. If not, I can make a PR by myself fixing it.

**Comment by fbartho** [comment]
My proposal here: https://github.com/infinitered/reactotron-react-native/issues/17#issuecomment-490688562 would also fix this issue.

**Comment by italomlp** [comment]
@fbartho your proposal sounds good and is very similar to what I thought at first. But maybe some props are optional for a reason. I opened this issue to know if the team (InfinityRed devs) really had that reason. If not, I'll make a PR when have free time.

**Comment by rmevans9** [comment]
There is not a real reason for it other then the core client doesn’t provide it so it complained about it. I’ll gladly accept any pr that makes this better

**Comment by rmevans9** [comment]
I believe this issue is fixed
